train_path: data/embed/laser-train.pt
valid_path: data/embed/laser-valid.pt
save_pooler_path: pooler/laser/dream-laser.pt
logging_path: log/dream-laser.log
train_type: vanilla
learning_rate: 1e-5
n_languages: 13
batch_size: 512
seed: 42
weights: [[1,1]]