train_path: data/embed/laser-train.pt
valid_path: data/embed/laser-valid.pt
save_pooler_path: pooler/laser/dream-laser-oracle.pt
logging_path: log/dream-laser-oracle.log
train_type: oracle_new
learning_rate: 1e-5
n_languages: 13
batch_size: 512
seed: 42
weights: [[1,1]]