train_path: ../data/cnli_train_jako_1m.pt
valid_path: ../data/cnli_valid_jako_1m.pt
model_name_or_path: mSimCSE/result/XLM-R-large-cnli
save_pooler_path: ../dream_cnli_boc.pt
logging_path: ../logs/dream_cnli_boc.log
train_type: boc
learning_rate: 1e-5
n_languages: 2
batch_size: 512
seed: 42
weights: [[1,1,1,1,1]]