train_path: ../data/tokenized/jako_test
valid_path: ../data/tokenized/jako_test
model_name_or_path: sentence-transformers/LaBSE
save_pooler_path: ../models/
logging_path: ../logs/meat_labse_finetune.log
train_type: boc
learning_rate: 1e-5
n_languages: 2
batch_size: 2
seed: 42
weights: [[1,1,1,1,1]]